applicationName: anti-guessing
database:
  # the name of your JDBC driver
  driverClass: org.mariadb.jdbc.Driver

  # the username
  user: ${DBUSERNAME}

  # the password
  password: ${DBPASSWORD}

  # the JDBC URL
  url: ${DBURL}

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.MariaDB53Dialect

  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s

  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* MyApplication Health Check */ SELECT 1"

  # the minimum number of connections to keep open
  minSize: 8

  # the maximum number of connections to keep open
  maxSize: 32

  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false

logging:
  # Root logger level
  level: INFO
  loggers:
    # This package will have DEBUG level
    "com.hamizan.app": DEBUG
    "org.hibernate.engine": ERROR
  appenders:
    # Log to stderr/netbeans output. Comment or remove this appenders if running in the server
    - type: console
      target: stderr
      timeZone: Asia/Kuala_Lumpur
      logFormat: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{5} [%thread] - %msg%n"      
    # Log to log file.
    # Log info, warnings and errors to log file.
    # Rolled over daily

    - type: file
      currentLogFilename: ./logs/anti-guessing.log
      archivedLogFilenamePattern: ./logs/anti-guessing-%d-%i.log.gz
      maxFileSize: 3MB
      archivedFileCount: 20
      # The timezone used to format dates. Without this your log time will be off
      timeZone: Asia/Kuala_Lumpur
      logFormat: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{5} [%thread] - %msg%n"

